// Code generated by hertz generator.

package handler

import (
	"context"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/lossfaller/hertz_demo/caller"
	"github.com/lossfaller/hertz_demo/constants"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	if err := caller.Provider.UpdateIDL(constants.NewIdlContent, map[string]string{}); err != nil {
		hlog.CtxInfof(ctx, "update idl error:%v", err)
	}
	c.JSON(consts.StatusOK, utils.H{
		"message": "pong",
	})
}
